name: xml_values

on: 
    workflow_call:
      outputs:
        projVersion: 
          value: ${{ jobs.get-xml-values.outputs.projVersion-output }}
        libGroup: 
          value: ${{ jobs.get-xml-values.outputs.libGroup-output }}
        libArtifact:
          value: ${{ jobs.get-xml-values.outputs.libArtifact-output }}
        libVersion:
          value: ${{ jobs.get-xml-values.outputs.libVersion-output }}
        
jobs:
  get-xml-values:
    runs-on: windows-latest
    outputs:
        projVersion-output: ${{ steps.values.outputs.projVersion }}
        libGroup-output: ${{ steps.values.outputs.libGroup }}
        libArtifact-output: ${{ steps.values.outputs.libArtifact }}
        libVersion-output: ${{ steps.values.outputs.libVersion }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: 'pom.xml'
    
      - name: values 
        id: values
        shell: pwsh
        run: |
          $x = [xml](gc pom.xml)

          $pvrs = $x.project.properties.revision | fl | Out-String
          echo $pvrs

          $lgrp = $x.project.parent.groupId | fl | Out-String
          echo $lgrp

          $lart = $x.project.parent.artifactId | fl | Out-String
          echo $lart
          
          $lver = $x.project.parent.version | fl | Out-String
          echo $lver

          echo "projVersion=$pvrs" >> $Env:GITHUB_OUTPUT
          echo "libGroup=$lgrp" >> $Env:GITHUB_OUTPUT
          echo "libArtifact=$lart" >> $Env:GITHUB_OUTPUT
          echo "libVersion=$lver" >> $Env:GITHUB_OUTPUT
