name: xml_dotnet_values

on: 
    workflow_call:
      outputs:
        libVersion:
          value: ${{ jobs.get-xml-values.outputs.libVersion-output }}
        
jobs:
  get-xml-values:
    runs-on: windows-latest
    outputs:
        libVersion-output: ${{ steps.values.outputs.libVersion }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: 'Novobanco.Services/Novobanco.Services.csproj'
    
      - name: values 
        id: values
        shell: pwsh
        run: |
          $x = [xml](gc Novobanco.Services.csproj)

          $lver = $x.SelectNodes("//PackageReference/@Version").Value

          $lver1 = $lver -split '\n' | Select-Object -First 1
          
          echo $lver1

          echo "libVersion=$lver1" >> $Env:GITHUB_OUTPUT
